## Settings
title: C0d3bR3aK3R - N3V3R TURN5 BACK
owner: "C0d3bR3ak3R"
url: "https://codebreaker444.github.io"
baseurl: "/"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "akiritsu@outlook.com"
github: "codebreaker444/codebreaker444.github.io"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Designed by DeerRIDER, All Rights Reserved"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "codebreaker"