
name: C0d3Br3ak3r
author: C0d3Br3ak3r
description: N3v3r Turn5 Back || My blog, My rules!
avatar: /images/cb-pebxil.png
footer-links:
  dribbble:
  email: codebreaker444@protonmail.com
  facebook:
  flickr:
  github: codebreaker444
  instagram:
  linkedin: 
  pinterest:
  rss: rss
  twitter: CodeBreaker444
  stackoverflow: 
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole: https://play.google.com/store/apps/dev?id=8331274631553271784&hl=en_IN


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

google_analytics: UA-73005973-1
url: https://blog.govardhanchitrada.me
enforce_ssl: https://blog.govardhanchitrada.me
baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded # You might prefer to minify using :compressed

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 5
paginate_path: /page:num/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

